/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasUtama;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

public class Pilihtiket extends javax.swing.JFrame {
    int hekonomi,hbisnis,heksekutif,hexpress;
    String nomor, nama, kode, namakereta, jenistiket, Harga, jurusan;
    String namatiket;
 
    public Pilihtiket() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Ht = new javax.swing.JTextField();
        rexpress = new javax.swing.JRadioButton();
        rbisnis = new javax.swing.JRadioButton();
        rekonomi = new javax.swing.JRadioButton();
        reksekutif = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cjurusan = new javax.swing.JComboBox<>();
        Nkereta = new javax.swing.JTextField();
        Ckode = new javax.swing.JComboBox<>();
        Tnama = new javax.swing.JTextField();
        Tnomor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/header/5.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 520, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1210, 110));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/icon/paper-plane.png"))); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 160, 40));

        Ht.setEditable(false);
        Ht.setBackground(new java.awt.Color(255, 255, 255));
        Ht.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        Ht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HtActionPerformed(evt);
            }
        });
        jPanel1.add(Ht, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 520, 30));

        rexpress.setBackground(new java.awt.Color(255, 255, 255));
        rexpress.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        rexpress.setText("Express");
        rexpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rexpressActionPerformed(evt);
            }
        });
        jPanel1.add(rexpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 150, -1));

        rbisnis.setBackground(new java.awt.Color(255, 255, 255));
        rbisnis.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        rbisnis.setText("Bisnis");
        rbisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbisnisActionPerformed(evt);
            }
        });
        jPanel1.add(rbisnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 150, -1));

        rekonomi.setBackground(new java.awt.Color(255, 255, 255));
        rekonomi.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        rekonomi.setText("Ekonomi");
        rekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekonomiActionPerformed(evt);
            }
        });
        jPanel1.add(rekonomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 130, -1));

        reksekutif.setBackground(new java.awt.Color(255, 255, 255));
        reksekutif.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        reksekutif.setText("Eksekutif");
        reksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reksekutifActionPerformed(evt);
            }
        });
        jPanel1.add(reksekutif, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 130, -1));

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel17.setText(":");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel15.setText(":");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 20, -1));

        jLabel16.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel16.setText("Harga Tiket");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Tiket");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel13.setText("Jurusan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel7.setText("Nama Kereta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel6.setText("Kode Kereta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel3.setText("Nama Penumpang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, -1));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel2.setText(":");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel5.setText(":");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 10, -1));

        jLabel14.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel14.setText(":");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        Cjurusan.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        Cjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CjurusanActionPerformed(evt);
            }
        });
        jPanel1.add(Cjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 520, 30));

        Nkereta.setEditable(false);
        Nkereta.setBackground(new java.awt.Color(255, 255, 255));
        Nkereta.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jPanel1.add(Nkereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 520, 30));

        Ckode.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        Ckode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Pilih Kode ----", "KA01", "KA02", "KA03", "KA04", "KA05" }));
        Ckode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkodeActionPerformed(evt);
            }
        });
        jPanel1.add(Ckode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 520, 30));

        Tnama.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jPanel1.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 520, 30));

        Tnomor.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        Tnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnomorActionPerformed(evt);
            }
        });
        jPanel1.add(Tnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 520, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/icon/close.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 480, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/people/3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 740, 640));

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel11.setText("No Transaksi");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/layout/4.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1270, 720));

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem1.setText("Menu Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem2.setText("Daftar Nama Kereta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem3.setText("Data Penumpang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem4.setText("Pilih Tiket");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1247, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        Mengambil Data Dari Display Form Pilih Tiket dan Untuk ditampilkan Ke Display
        Yang Ada di Form Transaksi Tiket
        */
        nomor   = Tnomor.getText();
        nama    = Tnama.getText();
        kode = (String) Ckode.getSelectedItem();
        namakereta = Nkereta.getText();
        jurusan = (String) Cjurusan.getSelectedItem();
        if (rekonomi.isSelected()){
            namatiket = "Ekonomi";
        }
        if (reksekutif.isSelected()){
            namatiket = "Eksekutif";
        }
        if (rbisnis.isSelected()){
            namatiket = "Bisnis";
        }
        if (rexpress.isSelected()){
            namatiket = "Express";
        }
        jenistiket = namatiket;
        Harga    = Ht.getText();
        Transaksi transaksi = new Transaksi(nomor, nama, kode, namakereta, jurusan, jenistiket, Harga);
        transaksi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HtActionPerformed

    private void rexpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rexpressActionPerformed
        //Menampilkan Harga Dalam Display Harga Ketika Memilih Express
        if(rexpress.isSelected()){
            Ht.setText(String.valueOf(hexpress));
        }
        rekonomi.setSelected(false);
        reksekutif.setSelected(false);
        rbisnis.setSelected(false);
    }//GEN-LAST:event_rexpressActionPerformed

    private void rbisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbisnisActionPerformed
        //Menampilkan Harga Dalam Display Harga Ketika Memilih Bisnis
        if(rbisnis.isSelected()){
            Ht.setText(String.valueOf(hbisnis));
        }
        rekonomi.setSelected(false);
        reksekutif.setSelected(false);
        rexpress.setSelected(false);
    }//GEN-LAST:event_rbisnisActionPerformed

    private void rekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekonomiActionPerformed
        //Menampilkan Harga Dalam Display Harga Ketika Memilih Ekonomi
        if(rekonomi.isSelected()){
            Ht.setText(String.valueOf(hekonomi));

        }
        rbisnis.setSelected(false);
        reksekutif.setSelected(false);
        rexpress.setSelected(false);
    }//GEN-LAST:event_rekonomiActionPerformed

    private void reksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reksekutifActionPerformed
        //Menampilkan Harga Dalam Display Harga Ketika Memilih Eksekutif
        if(reksekutif.isSelected()){
            Ht.setText(String.valueOf(heksekutif));
        }
        rekonomi.setSelected(false);
        rbisnis.setSelected(false);
        rexpress.setSelected(false);
    }//GEN-LAST:event_reksekutifActionPerformed

    private void CjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CjurusanActionPerformed
        //Tampilan Dalam Combo box Jurusan
        if(Cjurusan.getSelectedItem().equals("---- JURUSAN ----")){
            Ht.setText("");
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - SERANG")){
        //Menampilkan Harga Kedalam Display Harga Tiket Sesuai Pilihan  
            hekonomi=70000;
            hbisnis=150000;
            heksekutif=100000;
            hexpress=200000;
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - CILEGON")){
            hekonomi=75000;
            hbisnis=155000;
            heksekutif=105000;
            hexpress=205000;
        }
        else if(Cjurusan.getSelectedItem().equals("JAKARTA - BOGOR")){
            hekonomi=45000;
            hbisnis=70000;
            heksekutif=100000;
            hexpress=120000;
        }
        else if(Cjurusan.getSelectedItem().equals("JAKARTA - BANDUNG")){
            hekonomi=75000;
            hbisnis=250000;
            heksekutif=155000;
            hexpress=300000;
        }
        else if(Cjurusan.getSelectedItem().equals("JAKARTA - PEKALONGAN")){
            hekonomi=90000;
            hbisnis=150000;
            heksekutif=170000;
            hexpress=200000;
        }
        else if(Cjurusan.getSelectedItem().equals("JAKARTA - SEMARANG")){
            hekonomi=95000;
            hbisnis=170000;
            heksekutif=200000;
            hexpress=250000;
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - SOLO")){
            hekonomi=95000;
            hbisnis=155000;
            heksekutif=205000;
            hexpress=255000;
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - YOGYAKARTA")){
            hekonomi=100000;
            hbisnis=170000;
            heksekutif=250000;
            hexpress=300000;
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - SURABAYA")){
            hekonomi=150000;
            hbisnis=300000;
            heksekutif=270000;
            hexpress=350000;
        }else if(Cjurusan.getSelectedItem().equals("JAKARTA - MALANG")){
            hekonomi=155000;
            hbisnis=305000;
            heksekutif=275000;
            hexpress=355000;
        }
    }//GEN-LAST:event_CjurusanActionPerformed

    private void CkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkodeActionPerformed
       //Menu Pilih Kode Kereta
        if(Ckode.getSelectedItem().equals("KA01")){
            //Menampilkan Dalam Display Nama Kereta Ketika Memilih Kode Kereta
            Nkereta.setText("ARGOJATI");
            //Fokus Ketika Memilih Kode Kereta
            Cjurusan.removeAllItems();
            //Menampilkan Dalam Combo Box Jurusan Ketika Memilih Kode Kereta
            Cjurusan.addItem("---- JURUSAN ----");
            Cjurusan.addItem("JAKARTA - SERANG");
            Cjurusan.addItem("JAKARTA - CILEGON");
        }
        else if(Ckode.getSelectedItem().equals("KA02")){
            Nkereta.setText("ARGO PARAHYANGAN");//Nama Kereta
            Cjurusan.removeAllItems();
            Cjurusan.addItem("---- JURUSAN ----");
            Cjurusan.addItem("JAKARTA - BOGOR");
            Cjurusan.addItem("JAKARTA - BANDUNG");
        }
        else if(Ckode.getSelectedItem().equals("KA03")){
            Nkereta.setText("ARGO BROMO ANGGREK");//Nama Kereta
            Cjurusan.removeAllItems();
            Cjurusan.addItem("---- JURUSAN ----");
            Cjurusan.addItem("JAKARTA - PEKALONGAN");
            Cjurusan.addItem("JAKARTA - SEMARANG");
        }else if(Ckode.getSelectedItem().equals("KA04")){
            Nkereta.setText("ARGO WILIS");//Nama Kereta
            Cjurusan.removeAllItems();
            Cjurusan.addItem("---- JURUSAN ----");
            Cjurusan.addItem("JAKARTA - SOLO");
            Cjurusan.addItem("JAKARTA - YOGYAKARTA");
        }else if(Ckode.getSelectedItem().equals("KA05")){
            Nkereta.setText("GAYAMANA");//Nama Kereta
            Cjurusan.removeAllItems();
            Cjurusan.addItem("---- JURUSAN ----");
            Cjurusan.addItem("JAKARTA - SURABAYA");
            Cjurusan.addItem("JAKARTA - MALANG");
        }else if(Ckode.getSelectedItem().equals("---- Pilih Kode ----")){
            Nkereta.setText("");
            Cjurusan.getSelectedItem();
            Cjurusan.removeAllItems();
        }
    }//GEN-LAST:event_CkodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Button Kembali ke Muenu Utama
        Menuutama dnk = new Menuutama();
        dnk.setLocationRelativeTo(dnk);
        dnk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Menu Utama
        new Menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            //Daftar Nama Kereta
            new Daftarnamakereta().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pilihtiket.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //Dafatar Nama Penumpang
        new Datapenumpang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Pilih Kode Kereta Dan Jurusan
        new Pilihtiket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void TnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnomorActionPerformed
        try {
        // Menghitung jumlah data dalam tabel penumpang
        int jumlahData = tableModel.getRowCount();
        
        // Nomor transaksi baru adalah jumlah data + 1
        int nomorTransaksiBaru = jumlahData + 1;
        
        // Mengisi kolom nomor transaksi pada form dengan nomor baru
        Tnomor.setText(String.valueOf(nomorTransaksiBaru));
        
        // Lanjutkan dengan kode lain untuk menangani transaksi
        // ...
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_TnomorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilihtiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilihtiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilihtiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilihtiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilihtiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cjurusan;
    private javax.swing.JComboBox<String> Ckode;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JTextField Ht;
    private javax.swing.JTextField Nkereta;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tnomor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbisnis;
    private javax.swing.JRadioButton rekonomi;
    private javax.swing.JRadioButton reksekutif;
    private javax.swing.JRadioButton rexpress;
    // End of variables declaration//GEN-END:variables

    private static class tableModel {

        private static int getRowCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public tableModel() {
        }
    }
}
