/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasUtama;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Personal
 */
public class Tiket extends javax.swing.JFrame {

    String nomor3, nama3, kode3, namakereta3, jurusan3, jenistiket3;
    
    public Tiket(String nomor3, String nama3, String kode3, String namakereta3, String jurusan3, String jenistiket3) {
        initComponents();
        this.nomor3          = nomor3;
        this.nama3           = nama3;
        this.kode3           = kode3;
        this.namakereta3     = namakereta3;
        this.jurusan3        = jurusan3;
        this.jenistiket3     = jenistiket3;
        Tno.setText         (""+this.nomor3);
        Tnama.setText       (""+this.nama3);
        Tkode.setText       (""+this.kode3);
        Tnamakrt.setText    (""+this.namakereta3);
        Tjurusan.setText    (""+this.jurusan3);
        Tjenis.setText      (""+this.jenistiket3);
    }

    private Tiket() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Tjenis = new javax.swing.JTextField();
        Tnama = new javax.swing.JTextField();
        Tkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tjurusan = new javax.swing.JTextField();
        Tnamakrt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Tno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel7.setText("Nama Kereta / Train Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 270, 20));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel4.setText("BOARDING PASS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 350, 60));

        jLabel33.setFont(new java.awt.Font("Tekton Pro", 1, 48)); // NOI18N
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 70, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tjenis.setEditable(false);
        Tjenis.setBackground(new java.awt.Color(255, 102, 0));
        Tjenis.setFont(new java.awt.Font("Tekton Pro", 1, 30)); // NOI18N
        Tjenis.setBorder(null);
        Tjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TjenisActionPerformed(evt);
            }
        });
        jPanel3.add(Tjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1140, 60));

        Tnama.setEditable(false);
        Tnama.setBackground(new java.awt.Color(255, 255, 255));
        Tnama.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        Tnama.setBorder(null);
        jPanel1.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 40));

        Tkode.setEditable(false);
        Tkode.setBackground(new java.awt.Color(255, 255, 255));
        Tkode.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        Tkode.setBorder(null);
        jPanel1.add(Tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 40));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel2.setText("Kode Kereta / Train Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Boarding pass must  be shown in the boarding gate and for Verification on the train");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 500, 20));

        Tjurusan.setEditable(false);
        Tjurusan.setBackground(new java.awt.Color(255, 255, 255));
        Tjurusan.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        Tjurusan.setBorder(null);
        jPanel1.add(Tjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 340, 40));

        Tnamakrt.setEditable(false);
        Tnamakrt.setBackground(new java.awt.Color(255, 255, 255));
        Tnamakrt.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        Tnamakrt.setBorder(null);
        jPanel1.add(Tnamakrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 380, 40));

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel5.setText("Jurusan / Major");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 240, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Wajib menunjukkan bukti identitas asli pada saat boarding dan pemeriksaan di kereta api");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 500, 20));

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel9.setText("Nama / Name ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 20));

        Tno.setEditable(false);
        Tno.setBackground(new java.awt.Color(255, 255, 255));
        Tno.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        Tno.setBorder(null);
        Tno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnoActionPerformed(evt);
            }
        });
        jPanel1.add(Tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 40));

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel10.setText("Kode Transaksi / Transaction Code");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/icon/money.png"))); // NOI18N
        jButton9.setText("Buy");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 130, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/icon/diskette.png"))); // NOI18N
        jButton2.setText("Data ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 130, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1000, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasUtama/kereta/1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 370, 240));

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem1.setText("Menu Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem2.setText("Daftar Nama Kereta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem3.setText("Data Penumpang");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jMenuItem4.setText("Pilih Tiket");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1010, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TjenisActionPerformed

    private void TnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Pilih Kode Kereta Dan Jurusan
        new Pilihtiket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Menu Utama
        new Menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            //Daftar Nama Kereta
            new Daftarnamakereta().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tiket.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //Data Nama Penumpang
        new Datapenumpang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Pilih Kode Kereta Dan Jurusan
        new Pilihtiket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Untuk Melihat Data Penumpang Yang Telah Terdaftar
        this.setVisible(false);
        Datapenumpang dp=new Datapenumpang();
        dp.setLocationRelativeTo(dp);
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tjenis;
    private javax.swing.JTextField Tjurusan;
    private javax.swing.JTextField Tkode;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tnamakrt;
    private javax.swing.JTextField Tno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
